test

diff --git a/.github/workflows/stm32build.yml b/.github/workflows/stm32build.yml
--- a/.github/workflows/stm32build.yml
+++ b/.github/workflows/stm32build.yml
@@ -20,26 +20,62 @@ jobs:
       # Expose matched filters as job 'packages' output variable
       packages: ${{ steps.filter.outputs.changes }}
     steps:
-      # gets file environment with submodule included for libraries
-      - uses: actions/checkout@v3
-      # For pull requests it's not necessary to checkout the code
-      - uses: dorny/paths-filter@v2
-        id: filter
-        with:
-          filters: |
-            AC: STM32/AC/**
-            AirconCtrl: STM32/AirconCtrl/**
-            DC: STM32/DC/**
-            LightController: STM32/LightController/**
-            OTP: STM32/OTP/**
-            Temperature: STM32/Temperature/**
+    # gets file environment with submodule included for libraries
+    - uses: actions/checkout@v3
+      with:
+        submodules: 'true'         
+    # For pull requests it's not necessary to checkout the code
+    - uses: dorny/paths-filter@v2
+      id: filter
+      with:
+        filters: |
+          AC: STM32/AC/**
+          AirconCtrl: STM32/AirconCtrl/**
+          DC: STM32/DC/**
+          LightController: STM32/LightController/**
+          OTP: STM32/OTP/**
+          Temperature: STM32/Temperature/**
+  run_tests:
+    needs: changes
+    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
+    strategy:
+      matrix:
+        # Parse JSON array containing names of all filters matching any of changed files
+        package: ${{ fromJSON(needs.changes.outputs.packages) }}
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3   # gets file environment with submodule included for libraries
+      with:
+        submodules: 'true'
+    # Check whether the unittest folder exist in the modified project. If so, run unittests.
+    - name: Check if unittests exist
+      id: unittests_exists
+      run: |
+        if [ -d "STM32/${{ matrix.package }}/UnitTesting" ]; then
+          echo 'exist=1' >> $GITHUB_ENV
+        else
+          echo 'exist=0' >> $GITHUB_ENV
+        fi
+    # Build and run unittests. If the unittest fails the line number is output.
+    - name: Run unittests
+      if: env.exist == '1'
+      run: |
+        cd "STM32/${{ matrix.package }}/UnitTesting"
+        cmake CMakeLists.txt
+        make
+        output=$(./CA_UnitTesting)
+        echo $output
+        if [[ $output =~ "failed" ]]; then 
+          echo "Test failed"
+          exit 1
+        fi
   build:
     needs: changes
     permissions:
       pull-requests: read
       contents: write
     # If no changes has been made to projects above do not build
-    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
+    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }} 
     strategy:
       matrix:
         # Parse JSON array containing names of all filters matching any of changed files
@@ -98,6 +134,7 @@ jobs:
         run: |
           zip -j ${{ matrix.package }}.zip STM32/${{ matrix.package }}/build/${{ matrix.package }}.elf STM32/${{ matrix.package }}/build/${{ matrix.package }}.bin
         shell: bash
+        
       - name: Set up Python 3.10
         uses: actions/setup-python@v3
         with:
